# Generated by Django 5.0 on 2023-12-08 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surgery_name', models.CharField(max_length=255)),
                ('surgery_date', models.DateField()),
                ('surgery_time', models.TimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'db_table': 'surgery',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.surgery')),
            ],
            options={
                'db_table': 'surgery_booking',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.surgery')),
            ],
            options={
                'db_table': 'surgery_room',
                'ordering': ['timestamp'],
            },
        ),
    ]
